# This is a basic workflow to help you get started with Actions

name: Verification

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      block_data:
        description: 'File url for custom test data for parse_block tests'
        required: false
        type: string
      verb_data:
        description: 'File url for custom test data for verbalize_number tests'
        required: false
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Download custom block data
        if: ${{ inputs.block_data != ''}}
        run: wget -nc -O "${{ github.workspace }}/custom_block_data.json" ${{ inputs.block_data }}
      - name: Download custom verb data
        if: ${{ inputs.verb_data != ''}}
        run: wget -nc -O "${{ github.workspace }}/custom_verb_data.json" ${{ inputs.verb_data }}
      - name: Test basic test cases
        if: ${{ inputs.verb_data == '' || inputs.block_data == '' }}
        run: |
          pip install pytest
          pytest test_cases.py --doctest-modules --junitxml=junit/test-results.xml
      - name: Test custom test cases
        if: ${{ inputs.verb_data != '' && inputs.block_data != '' }}
        run: |
          pip install pytest
          pytest test_cases.py --block_data="${{ github.workspace }}/custom_block_data.json" --verb_data="${{ github.workspace }}/custom_verb_data.json" --doctest-modules --junitxml=junit/test-results.xml